In [1]:
import numpy as np

In [2]:
X = np.array([[1, 0, 1, 0],
     [1, 0, 1, 1],
     [0, 1, 0, 1]])
Y = np.array([[1],
             [1],
             [0]])
lr = 1



In [3]:
wh = np.random.uniform(low=0, high=1, size=(4,3))
bh = np.random.uniform(low=0, high=1, size=(1,3))
wout = np.random.uniform(low=0, high=1, size=(3,1))
bout = np.random.uniform(low=0, high=1, size=(1,1))
print(wh)
print(bh)
print(wout)
print(bout)

[[ 0.42689463  0.1454299   0.93919079]
 [ 0.47595447  0.10026753  0.58240361]
 [ 0.38481045  0.7758597   0.47594849]
 [ 0.41094801  0.23264197  0.0805603 ]]
[[ 0.01344228  0.16688243  0.74481094]]
[[ 0.81635063]
 [ 0.4416652 ]
 [ 0.53382643]]
[[ 0.76682471]]


In [4]:
'''wh = np.array([[0.42, 0.88, 0.55],
     [0.1, 0.73, 0.68],
     [0.6, 0.18, 0.47],
     [0.92, 0.11, 0.52]])
bh = np.array([0.46, 0.72, 0.08])
wout = np.array([[0.3],
                [0.25], 
                [0.23]])
bout = np.array([0.69])
'''

'wh = np.array([[0.42, 0.88, 0.55],\n     [0.1, 0.73, 0.68],\n     [0.6, 0.18, 0.47],\n     [0.92, 0.11, 0.52]])\nbh = np.array([0.46, 0.72, 0.08])\nwout = np.array([[0.3],\n                [0.25], \n                [0.23]])\nbout = np.array([0.69])\n'

In [5]:
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

In [6]:
def sigmoid_der(xprime):
    return xprime * (1 - xprime)

In [7]:
hidden_layer = X.dot(wh) + bh
print(hidden_layer)
hidden_layer = sigmoid(hidden_layer)
print(hidden_layer)

[[ 0.82514736  1.08817202  2.15995021]
 [ 1.23609537  1.320814    2.24051051]
 [ 0.90034476  0.49979194  1.40777485]]
[[ 0.69532789  0.74803735  0.89659493]
 [ 0.77488363  0.7893171   0.90382884]
 [ 0.71102035  0.62241043  0.80341474]]


In [8]:
output_layer = hidden_layer.dot(wout) + bout
print(output_layer)
output_layer = sigmoid(output_layer)
print(output_layer)

[[ 2.1434642 ]
 [ 2.23050306]
 [ 2.05104767]]
[[ 0.89505645]
 [ 0.90295545]
 [ 0.88605344]]


In [9]:
err_output = Y - output_layer
print(err_output)

[[ 0.10494355]
 [ 0.09704455]
 [-0.88605344]]


In [10]:
slope_out = sigmoid_der(output_layer)
print(slope_out)

[[ 0.0939304 ]
 [ 0.08762691]
 [ 0.10096274]]


In [11]:
slope_hidden = sigmoid_der(hidden_layer)
print(slope_hidden)

[[ 0.21184702  0.18847748  0.09271246]
 [ 0.17443899  0.16629561  0.08692227]
 [ 0.20547041  0.23501569  0.15793949]]


In [12]:
d_output = err_output * slope_out
print(d_output)

[[ 0.00985739]
 [ 0.00850371]
 [-0.08945839]]


In [13]:
err_hidden = d_output.dot(wout.T)
print(d_output.shape, wout.shape)
print(err_hidden)

(3, 1) (3, 1)
[[ 0.00804709  0.00435367  0.00526214]
 [ 0.00694201  0.00375579  0.00453951]
 [-0.07302941 -0.03951066 -0.04775525]]


In [14]:
d_hidden = err_hidden*slope_hidden
print(d_hidden)

[[ 0.00170475  0.00082057  0.00048787]
 [ 0.00121096  0.00062457  0.00039458]
 [-0.01500538 -0.00928562 -0.00754244]]


In [15]:
wout = wout + hidden_layer.T.dot(d_output) * lr
print(wout)

[[ 0.7661874 ]
 [ 0.40007119]
 [ 0.47847823]]


In [16]:
wh = wh+ X.T.dot(d_hidden) * lr
print(wh)

[[ 0.42981034  0.14687504  0.94007324]
 [ 0.46094909  0.09098191  0.57486117]
 [ 0.38772616  0.77730484  0.47683093]
 [ 0.39715359  0.22398092  0.07341244]]


In [17]:
bh = bh + np.sum(d_hidden, axis=0) * lr
bout = bout + np.sum(d_output, axis=0)*lr
print(bh, bout)

[[ 0.0013526   0.15904194  0.73815095]] [[ 0.69572742]]
